### ISSUE TITLE
Incorrect variable name

### ISSUE THREAD

**Issue by rniemand** [home-assistant/example-custom-config#1]
Should this not be `who` as opposed to `title` :)

https://github.com/home-assistant/example-custom-config/blob/5d7bb1c3472e81152b7299361cc70c6a6c96669c/panels/hello_world.html#L8

**Comment by pelson** [comment]
Yep, it should. @rniemand, would you be interested in submitting a PR?

**Comment by rniemand** [comment]
Created https://github.com/home-assistant/example-custom-config/pull/2
