### ISSUE TITLE
Include example with config_flow

### ISSUE THREAD

**Issue by meichthys** [home-assistant/example-custom-config#17]
It would be helpful to have an example that implements a config_flow that allows home-assistant users to configure the integration using the home-assistant gui.

**Comment by balloob** [comment]
In a HA dev environment, type `python3 -m script.scaffold integration`

**Comment by meichthys** [comment]
@balloob, Wow, a response from the man himself! Thanks! I did see that scaffold in the tutorial, but it would be nice to see an example of how some of the 'ToDo' items can be implemented. For now I can browse through some of the existing integrations like @frenck's Adguard Integration that uses a config_flow.

Keep up the good work!
