### ISSUE TITLE
Recommendations for a async polling example

### ISSUE THREAD

**Issue by sillyfrog** [home-assistant/example-custom-config#19]
@balloob : further to the [async push example](https://github.com/home-assistant/example-custom-config/pull/18) you helped me with, I'm looking to do the same (as discussed) with a polling implementation.

I'm still new to HA, so please excuse the newbie questions :) 

Do you have any thoughts as to which way I should go for the example, "Coordinated" or "Separate" (as per here: https://developers.home-assistant.io/docs/integration_fetching_data/#coordinated-single-api-poll-for-data-for-all-entities )? Just wrapping my head around it, and the implementation of the two I think will end up quite different.

Cheers.

**Comment by balloob** [comment]
Yeah, it should be an example using the data update coordinator.
