### ISSUE TITLE
Do these examples still represent best practices?

### ISSUE THREAD

**Issue by joejulian** [home-assistant/example-custom-config#29]
There's no config_flow and nothing's async. Do these still represent best practices?

**Comment by balloob** [comment]
There are some async examples too like https://github.com/home-assistant/example-custom-config/tree/master/custom_components/detailed_hello_world_push

Not sure if they are all following the very latest standards.

**Comment by marvin-w** [comment]
I updated this specific example in https://github.com/home-assistant/example-custom-config/pull/30

**Comment by joejulian** [comment]
Thank you
