### ISSUE TITLE
Integration error: hello_world - Integration 'hello_world' not found

### ISSUE THREAD

**Issue by VoiceOfSoftware** [home-assistant/example-custom-config#34]
I copied everything from Home Assistant's own [hello_world](https://github.com/home-assistant/example-custom-config/tree/master/custom_components/hello_world) example, and still get the error message "Integration error: hello_world - Integration 'hello_world' not found." when I click [Check Configuration]
I used HA's own File editor plugin to create the file /config/custom_components/hello_world/\_\_init\_\_.py, and pasted the contents from GitHub into it. Same for /config/custom_components/hello_world/manifest.json
Then, per the instructions, I edited /config/configuration.yaml to add a single new line near the top:
hello_world:

**Comment by ludeeus** [comment]
You need to restart Home Assistant 1 time before you add the configuration for it to make Home Assistant aware of the new integration.
