### ISSUE TITLE
Complete the example sensor please

### ISSUE THREAD

**Issue by HAEdwin** [home-assistant/example-custom-config#40]
It would be nice if the example sensor is enriched with how to update the value of the sensor. That would complete this snippet. Only then will you have a complete working example.

**Comment by MartinHjelmare** [comment]
Is there something else than this you're looking for?

https://github.com/home-assistant/example-custom-config/blob/8defd50b9b5aede370cd9b51e6cc8c9f05a6b6ca/custom_components/example_sensor/sensor.py#L33-L38

**Comment by HAEdwin** [comment]
Sorry I really don't understand the example. Suppose I want to update the temperature outside the sensor definition (class) with the value 24. How should I do that? Does that work like this: `ExampleSensor.update(24)` ?

**Comment by MartinHjelmare** [comment]
You should not access the entity from outside. The entity should access some client instance or data storage where it can get new data.

For polling integrations we recommend using our DataUpdateCoordinator helper and CoordinatorEntity class.

https://developers.home-assistant.io/docs/integration_fetching_data#coordinated-single-api-poll-for-data-for-all-entities

The latter is outside the scope of the sensor example here.

**Comment by HAEdwin** [comment]
I completely understand how it works now, I was thinking the other way around. Thank you very much for this example and your work!
