### ISSUE TITLE
Provide code for example_sensor/__init__.py

### ISSUE THREAD

**Issue by realmayus** [home-assistant/example-custom-config#42]
When I try to add the `example_sensor` example to my HA instance, I get the following error after restarting:
![Screenshot 2023-04-07 at 22 04 18](https://user-images.githubusercontent.com/38134006/230671874-33b6c678-e1c5-4ca3-87d5-83c59e7c3865.png)

The __init__.py file in the example is empty. What do I have to add for the example to work?

**Comment by davet2001** [comment]
I suggest you try adding it using the existing name 'example_sensor' first, then go from there.

**Comment by davet2001** [comment]
@realmayus please reopen of you are still experiencing a problem.
