### ISSUE TITLE
Error when adding Example sensor

### ISSUE THREAD

**Issue by Jimmy2027** [home-assistant/example-custom-config#52]
Hello,
I would like to try out the example sensor to build on it but when I copy the folder over to `custom_components/example_sensor/` and add the following lines to my config:
```
# Example configuration.yaml entry
sensor:
  - platform: example_sensor
```

my config check fails with:
`Invalid config for [sensor]: required key not provided @ data['platform']. Got None. (See /config/configuration.yaml, line 44).`

Am I missing something?

**Comment by MartinHjelmare** [comment]
Check your config file. It's working for me.

**Comment by Jimmy2027** [comment]
True, I rewrote it by hand and now it works. Thanks!
