### ISSUE TITLE
Error occurred loading flow for integration remote_homeassistant: cannot import name 'DATA_CUSTOMIZE' from 'homeassistant.config' (/usr/src/homeassistant/homeassistant/config.py) 

### ISSUE THREAD

**Issue by pooyair** [home-assistant/example-custom-config#74]
I have provided 'DATA_CUSTOMIZE' and other Errors and Warning logs with the latest HA Stable Versions . please find the Log following and let me know if you have any questions or concerns.

Error occurred loading flow for integration remote_homeassistant: cannot import name 'DATA_CUSTOMIZE' from 'homeassistant.config' (/usr/src/homeassistant/homeassistant/config.py)

#####################################

> Logger: homeassistant.setup
> Source: setup.py:334
> First occurred: 2:51:38 PM (1 occurrences)
> Last logged: 2:51:38 PM
> 
> Setup failed for custom integration 'remote_homeassistant': Unable to import component: cannot import name 'DATA_CUSTOMIZE' from 'homeassistant.config' (/usr/src/homeassistant/homeassistant/config.py)
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/loader.py", line 1011, in async_get_component
> comp = await self.hass.async_add_import_executor_job(
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
> result = self.fn(*self.args, **self.kwargs)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/usr/src/homeassistant/homeassistant/loader.py", line 1071, in _get_component
> ComponentProtocol, importlib.import_module(self.pkg_path)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
> return func(*args, **kwargs)
> ^^^^^^^^^^^^^^^^^^^^^
> File "/usr/local/lib/python3.12/importlib/init.py", line 90, in import_module
> return _bootstrap._gcd_import(name[level:], package, level)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "", line 1387, in _gcd_import
> File "", line 1360, in _find_and_load
> File "", line 1331, in _find_and_load_unlocked
> File "", line 935, in _load_unlocked
> File "", line 995, in exec_module
> File "", line 488, in _call_with_frames_removed
> File "/config/custom_components/remote_homeassistant/init.py", line 22, in
> from homeassistant.config import DATA_CUSTOMIZE
> ImportError: cannot import name 'DATA_CUSTOMIZE' from 'homeassistant.config' (/usr/src/homeassistant/homeassistant/config.py)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
> component = await integration.async_get_component()
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/usr/src/homeassistant/homeassistant/loader.py", line 1031, in async_get_component
> self._component_future.result()
> File "/usr/src/homeassistant/homeassistant/loader.py", line 1023, in async_get_component
> comp = self._get_component()
> ^^^^^^^^^^^^^^^^^^^^^
> File "/usr/src/homeassistant/homeassistant/loader.py", line 1071, in _get_component
> ComponentProtocol, importlib.import_module(self.pkg_path)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
> return func(*args, **kwargs)
> ^^^^^^^^^^^^^^^^^^^^^
> File "/usr/local/lib/python3.12/importlib/init.py", line 90, in import_module
> return _bootstrap._gcd_import(name[level:], package, level)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "", line 1387, in _gcd_import
> File "", line 1360, in _find_and_load
> File "", line 1331, in _find_and_load_unlocked
> File "", line 935, in _load_unlocked
> File "", line 995, in exec_module
> File "", line 488, in _call_with_frames_removed
> File "/config/custom_components/remote_homeassistant/init.py", line 22, in
> from homeassistant.config import DATA_CUSTOMIZE
> ImportError: cannot import name 'DATA_CUSTOMIZE' from 'homeassistant.config' (/usr/src/homeassistant/homeassistant/config.py)
> What version of Home Assistant Core has the issue?

2024.11.0

Core
2024.11.0
Supervisor
2024.11.2
Operating System
13.2
Frontend
20241106.0

**Comment by joostlek** [comment]
Please raise at the custom component issue tracker.

**Comment by pooyair** [comment]
Sigh! I Already did. Bye!
