### ISSUE TITLE
Cannot set up example mqtt_basic

### ISSUE THREAD

**Issue by trungnte** [home-assistant/example-custom-config#8]
Hi all,
I had tried to integrate the MQTT basic to home assistant. I copied folder mqtt_basic to my config custom_components, and modify configuration.yaml like guidlines. I got error log:

> 2019-04-16 02:50:42 ERROR (MainThread) [homeassistant.config] Invalid config for [mqtt_basic]: [homeassistant] is an invalid option for [mqtt_basic]. C                                                heck: mqtt_basic->homeassistant. (See /home/trung/work/my-ha/configuration.yaml, line 87). Please check the docs at https://home-assistant.io/compon                                                ents/mqtt_basic/
2019-04-16 02:50:42 ERROR (MainThread) [homeassistant.setup] Setup failed for mqtt_basic: Invalid config.

Would you like to give a advise for this issue?
Thank you very much. 
I attached my configuration.yaml. I just rename the extension file to upload.

[configuration.yaml.txt](https://github.com/home-assistant/example-custom-config/files/3082896/configuration.yaml.txt)

**Comment by Gaardsholt** [comment]
I have the same issue - did you find a solution for this?

**Comment by Handkep** [comment]
i have the same issue :( is there any solution?
